In [6]:
import numpy as np

In [144]:
import sys

### Numpy array basics

In [7]:
np.array([1,2,3])

array([1, 2, 3])

In [8]:
a=np.array([1,2,3,4])

In [9]:
b=np.array([1,2,3,4,5,6,7,8,9])

In [10]:
a[2],b[1]

(3, 2)

In [12]:
b[1:4]

array([2, 3, 4])

In [13]:
b[0::2]

array([1, 3, 5, 7, 9])

In [14]:
b[-1:1:-1]

array([9, 8, 7, 6, 5, 4, 3])

In [15]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
b[0],b[7],b[3]

(1, 8, 4)

### Something you can do in Numpy but not in regular python

In [16]:
b[[0,7,3]]

array([1, 8, 4])

### Numpy array types

In [18]:
c=np.array([1.2,3.4,5.6,9.8])

In [19]:
c.dtype

dtype('float64')

In [20]:
a.dtype

dtype('int32')

In [21]:
b.dtype

dtype('int32')

In [25]:
np.array([1,2,3,4,5], dtype=np.float64)

array([1., 2., 3., 4., 5.])

In [36]:
e=np.array(['a','b','c'])

In [37]:
e.dtype

dtype('<U1')

### Dimensions,Matrices,2d and 3d arrays

In [39]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [40]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
A[0][1]

2

In [43]:
A[0]

array([1, 2, 3])

In [44]:
A[2]

array([7, 8, 9])

In [45]:
A[0,1]

2

In [47]:
A[2,2]

9

In [48]:
A[1]= np.array([11,12,13])

In [49]:
A

array([[ 1,  2,  3],
       [11, 12, 13],
       [ 7,  8,  9]])

In [50]:
A[2]=99

In [51]:
A

array([[ 1,  2,  3],
       [11, 12, 13],
       [99, 99, 99]])

In [52]:
A.shape

(3, 3)

In [53]:
A.size

9

In [54]:
A.ndim

2

In [56]:
B = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [11,12,13],
        [14,15,16]
    ]
])

In [57]:
B

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [58]:
B.ndim

3

In [59]:
B.shape

(2, 2, 3)

In [60]:
B.size

12

### Slicing of matrices

In [61]:
A

array([[ 1,  2,  3],
       [11, 12, 13],
       [99, 99, 99]])

In [62]:
A[0:2]

array([[ 1,  2,  3],
       [11, 12, 13]])

In [63]:
A[:,:2]

array([[ 1,  2],
       [11, 12],
       [99, 99]])

In [64]:
A[:2,:2]

array([[ 1,  2],
       [11, 12]])

In [65]:
A[:2,2:]

array([[ 3],
       [13]])

### Statistics Summary

In [66]:
a = np.array([1,2,3,4])

In [67]:
a

array([1, 2, 3, 4])

In [69]:
a.sum()

10

In [70]:
a.mean()

2.5

In [71]:
a.std()

1.118033988749895

In [73]:
a.var()

1.25

In [74]:
A

array([[ 1,  2,  3],
       [11, 12, 13],
       [99, 99, 99]])

In [76]:
A.sum()

339

In [77]:
A.mean()

37.666666666666664

In [78]:
A.std()

43.56604182158393

In [79]:
A.var()

1898.0

In [81]:
A.sum(axis=0)

array([111, 113, 115])

In [82]:
A.sum(axis=1)

array([  6,  36, 297])

In [83]:
A.mean(axis=0)

array([37.        , 37.66666667, 38.33333333])

In [85]:
A.mean(axis=1) #similar thing can be done for std and var

array([ 2., 12., 99.])

### Broadcasting and Vectorized operations

In [90]:
a=np.arange(4)

In [91]:
a

array([0, 1, 2, 3])

##### Broadcasting between array and scalar

In [92]:
a+10

array([10, 11, 12, 13])

In [93]:
a*10

array([ 0, 10, 20, 30])

In [94]:
a+=100

In [95]:
a

array([100, 101, 102, 103])

##### List comprehension in python

In [96]:
l= [2,4,6,8]

In [100]:
[i*10 for i in l]

[20, 40, 60, 80]

##### Compared to list comprehension in python:
##### -vectorized operations in numpy is much more faster and optimized

##### Broadcasting between array and array

In [103]:
a=np.arange(4)

In [104]:
a

array([0, 1, 2, 3])

In [106]:
b=np.array([10,20,30,40])

In [107]:
b

array([10, 20, 30, 40])

In [108]:
a+b

array([10, 21, 32, 43])

In [109]:
a*b

array([  0,  20,  60, 120])

### Boolean Arrays 

In [110]:
a=np.arange(4)

In [111]:
a

array([0, 1, 2, 3])

In [116]:
a[0],a[-1]

(0, 3)

In [117]:
a[[0,-1]]

array([0, 3])

##### if u pass a boolean array to a, a resultant numpy array gets returned

In [119]:
a[[True,False,True,False]]

array([0, 2])

In [120]:
a

array([0, 1, 2, 3])

##### When you perform a boolean operation, you get a resultant boolean numpy array which in turn can be used for filtering

In [121]:
a>=1

array([False,  True,  True,  True])

In [122]:
a[a>=1]

array([1, 2, 3])

In [123]:
a.mean()

1.5

In [125]:
a[a>a.mean()]

array([2, 3])

In [128]:
a[~(a>a.mean())]

array([0, 1])

In [129]:
a[(a>1)&(a<3)]

array([2])

In [130]:
a[(a<1)|(a>2)]

array([0, 3])

In [134]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [131]:
A

array([[ 1,  2,  3],
       [11, 12, 13],
       [99, 99, 99]])

In [132]:
A<=13

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [133]:
A[A<=13]

array([ 1,  2,  3, 11, 12, 13])

### Linear Algebra

In [135]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [137]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [138]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [139]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [140]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [141]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [142]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

### Size of Objects in Memory

In [145]:
sys.getsizeof(1)

28

In [147]:
np.dtype(int).itemsize

4

In [156]:
np.array([1,2,3]).itemsize

4

In [160]:
np.dtype('int32').itemsize

4

### Measuring performance btw reg. python and numpy

In [193]:
l = list(range(100000))

In [195]:
a = np.arange(100000)

In [196]:
%time np.sum(a ** 2)

Wall time: 998 µs


216474736

In [197]:
%time sum([x ** 2 for x in l])

Wall time: 32.9 ms


333328333350000